Repository Swent-Fall-2024-team-10/leazy, pull requests merged in 2024-11, with the labels that each got.

#114 Feature: Landlord Profile Creation
  app/index.tsx
  app/screens/auth/SignUpScreen.tsx
  app/screens/landlord/LandlordFormScreen.tsx
  firebase/firestore/firestore.ts
  types/types.ts
Labels: enhancement

#106 Feature upload all pictures at once (#103)
  app/__tests__/unit/cache.test.ts
  app/screens/camera/CapturedMediaScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/utils/cache.ts
  package-lock.json
  package.json
Labels: enhancement

#120 Unit testing for firestore functions and Tenant Form
  .gitignore
  app/__tests__/TenantFormScreen.test.tsx
  app/__tests__/unit/firebase.test.tsx
  app/components/buttons/SubmitButton.tsx
  app/components/forms/text_input.tsx
  app/screens/tenant/TenantFormScreen.tsx
  firebase/firebase.ts
  firebase/firestore/firestore.ts
  jest/jest.config.js
  jest/setup.js
  package-lock.json
  package.json
  tsconfig.json
Labels: testing

#124 Test/firestore more tests
  app/__tests__/unit/firebase.test.tsx
  app/__tests__/unit/firestore.test.ts
  app/screens/auth/SignUpScreen.tsx
  firebase/firestore/firestore.ts
  package-lock.json
  types/types.ts
Labels: testing

#121 Test/darius' screens and others
  app/__tests__/CodeApprovedScreen.test.tsx
  app/__tests__/CodeEntryScreen.test.tsx
  app/__tests__/CreateNewCode.test.tsx
  app/__tests__/HomepageScreen.test.tsx
  app/__tests__/MyRentScreen.test.tsx
  app/__tests__/SettingsScreen.test.tsx
  app/__tests__/SharedElementsScreen.test.tsx
  app/__tests__/SubrentScreen.test.tsx
  app/components/Header.tsx
  app/components/buttons/SubmitButton.tsx
  app/screens/auth/CodeApprovedScreen.tsx
  app/screens/auth/CodeEntryScreen.tsx
  app/screens/auth/SignUpScreen.tsx
  app/screens/landlord/CreateNewCode.tsx
  app/screens/tenant/MyRentScreen.tsx
  app/screens/tenant/SettingsScreen.tsx
  app/screens/tenant/SubrentScreen.tsx
  firebase/firestore/firestore.ts
  package-lock.json
  package.json
  types/types.ts
Labels: testing

#129 test: unit tests for all components inside buttons
  app/__tests__/CameraButton.test.tsx
  app/__tests__/Close.test.tsx
  app/__tests__/CloseConfirmation.test.tsx
  app/__tests__/SubmitButton.test.tsx
  app/components/buttons/CameraButton.tsx
  app/components/buttons/Close.tsx
  app/components/buttons/CloseConfirmation.tsx
  package.json
Labels: testing

#107 Timer, backend and CloudFunction for Washing Machines
  app/components/CustomButton.tsx
  app/index.tsx
  app/screens/laundry_machines/ManageMachinesScreen.tsx
  app/screens/laundry_machines/WashingMachineScreen.tsx
  firebase.json
  firebase/firestore/firestore.ts
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
  package-lock.json
  package.json
  types/types.ts
Labels: enhancement

#133 test: unit testing for the remaining components
  app/__tests__/AdaptiveButton.test.tsx
  app/__tests__/CustomButton.test.tsx
  app/__tests__/CustomPicker.test.tsx
  app/__tests__/CustomPopUp.test.tsx
  app/__tests__/CustomTextField.test.tsx
  app/__tests__/Spacer.test.tsx
  app/__tests__/StatusBadge.test.tsx
  app/__tests__/StatusDropdown.test.tsx
  app/components/AdaptiveButton.tsx
  app/components/CustomPicker.tsx
  app/components/CustomPopUp.tsx
  app/components/CustomTextField.tsx
  app/components/StatusBadge.tsx
  app/components/StatusDropdown.tsx
  app/screens/messaging/MessagingScreen.tsx
  app/screens/messaging/index.ts
Labels: testing

#132 High Coverage Tests for Authentication Module
  app/__tests__/SignInScreen.test.tsx
  app/__tests__/SignUpScreen.test.tsx
  app/__tests__/cache.test.ts
  app/__tests__/flow.yml
  app/__tests__/unit/auth.test.ts
  app/__tests__/unit/firebase.test.tsx
  app/__tests__/unit/storage.test.ts
  app/screens/auth/SignInScreen.tsx
  app/screens/auth/SignUpScreen.tsx
  jest/setup.js
  package.json
  types/types.ts
Labels: testing

#154 Figma design for the situation report screen
  app/components/buttons/CameraButton.tsx
Labels: figma

#160 UI : Screen for the situation Report form.
  app/Navigators/LandlordDrawerNavigator.tsx
  app/__tests__/SeparationLine.test.tsx
  app/__tests__/SituationReportTest.test.tsx
  app/__tests__/TickingBox.test.tsx
  app/__tests__/firestore.test.ts
  app/components/SeparationLine.tsx
  app/components/buttons/CloseConfirmation.tsx
  app/components/forms/TickingBox.tsx
  app/screens/landlord/SituationReportScreen.tsx
  jest/setup.js
  package-lock.json
  package.json
  styles/styles.ts
Labels: enhancement

#163 Tests for 4 screens
  app/__tests__/unit/IssueDetailsScreen.test.tsx
  app/__tests__/unit/LandlordFormScreen.test.tsx
  app/__tests__/unit/LandlordListIssues.test.tsx
  app/__tests__/unit/ListIssuesScreen.test.tsx
  app/components/StatusDropdown.tsx
  app/screens/issues_landlord/LandlordListIssuesScreen.tsx
  app/screens/issues_tenant/IssueDetailsScreen.tsx
  app/screens/issues_tenant/ListIssueScreen.tsx
  app/utils/StatusHelper.ts
  firebase/auth/auth.ts
  package.json
Labels: testing

#159 Added tests for sign-in and sign-up screens
  app/__tests__/SignInScreen.test.tsx
  app/__tests__/SignUpScreen.test.tsx
  app/components/CustomPicker.tsx
  app/index.tsx
  app/screens/auth/SignInScreen.tsx
  app/screens/auth/SignUpScreen.tsx
  app/screens/laundry_machines/CreateWashingMachineScreen.tsx
  tests_examples/snapshot_test/ExampleSnapshot.tsx
  tests_examples/snapshot_test/__tests__/Profile-test.tsx
  tests_examples/snapshot_test/__tests__/__snapshots__/Profile-test.tsx.snap
  tests_examples/testing_basic/UnitTestComponent.tsx
  tests_examples/testing_basic/__tests__/BasicComponent-test.tsx
  tests_examples/testing_mocking/ExampleApi.tsx
  tests_examples/testing_mocking/UserProfile.tsx
  tests_examples/testing_mocking/__tests__/UserProfile-test.tsx
  tests_examples/testing_props/ExampleWithProps.tsx
  tests_examples/testing_props/__tests__/Greeting-test.tsx
  tests_examples/testing_states/ExampleWithState.tsx
  tests_examples/testing_states/__tests__/SimpleCounter-test.tsx
  types/types.ts
Labels: testing

#178 Bugfix/firestore functions
  app/Navigators/AuthContext.tsx
  app/Navigators/RootNavigator.tsx
  app/__tests__/AuthContext.test.tsx
  app/__tests__/CodeEntryScreen.test.tsx
  app/__tests__/CreateNewCode.test.tsx
  app/__tests__/ReportScreen.test.tsx
  app/__tests__/RootNavigator.test.tsx
  app/__tests__/SignInScreen.test.tsx
  app/__tests__/SignUpScreen.test.tsx
  app/__tests__/TenantFormScreen.test.tsx
  app/__tests__/cache.test.ts
  app/__tests__/firebase.test.tsx
  app/__tests__/unit/LandlordListIssues.test.tsx
  app/__tests__/unit/cache.test.ts
  app/components/GoogleSignInButton.tsx
  app/components/buttons/CameraButton.tsx
  app/components/buttons/Close.tsx
  app/components/buttons/CloseConfirmation.tsx
  app/screens/auth/CodeEntryScreen.tsx
  app/screens/auth/LandlordFormScreen.tsx
  app/screens/auth/TenantFormScreen.tsx
  app/screens/issues_landlord/LandlordListIssuesScreen.tsx
  app/screens/issues_tenant/IssueDetailsScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/screens/landlord/CreateNewCode.tsx
  firebase/firestore/firestore.ts
  package-lock.json
  types/types.ts
Labels: bug, testing

#183 Feature/backend situation report
  .gitignore
  app/__tests__/SituationReport.firebase.test.ts
  app/__tests__/SituationReport.test.ts
  app/screens/landlord/SituationReportScreen.tsx
  app/utils/SituationReport.ts
  firebase/firestore/firestore.ts
  firestore-debug.log
  package-lock.json
  package.json
  types/types.ts
Labels: enhancement, testing

#186 Figma designs and wireframes for dashboard and residence editing
  app/__tests__/unit/IssueDetailsScreen.test.tsx
Labels: figma
