Repository Swent-Fall-2024-team-10/leazy, pull requests merged in 2024-12, with the labels that each got.

#213 Feature : situation report creation screen implementation
  .eslintrc.json
  .prettierrc
  app/Navigators/LandlordDrawerNavigator.tsx
  app/__tests__/SituationReport.test.ts
  app/__tests__/SituationReportCreationScreen.test.tsx
  app/__tests__/SituationReportTest.test.tsx
  app/components/buttons/CloseConfirmation.tsx
  app/components/buttons/SubmitButton.tsx
  app/screens/auth/LandlordFormScreen.tsx
  app/screens/auth/TenantFormScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/screens/landlord/SituationReport/SituationReportCreationScreen.tsx
  app/screens/landlord/SituationReport/SituationReportScreen.tsx
  app/screens/landlord/SituationReportScreen.tsx
  app/screens/landlord/index.ts
  app/utils/SituationReport.ts
  package-lock.json
  package.json
  sonar-project.properties
  styles/SituationReportStyling.ts
  styles/styles.ts
Labels: enhancement, testing

#214 Implement back-end for messaging
  app/Navigators/IssueStackNavigator.tsx
  app/__tests__/LandlordContext.test.tsx
  app/__tests__/MessagingScreen.test.tsx
  app/__tests__/ReportScreen.test.tsx
  app/__tests__/chat.test.ts
  app/__tests__/unit/IssueDetailsScreen.test.tsx
  app/components/messaging/CustomBubble.tsx
  app/components/messaging/CustomInputToolbar.tsx
  app/screens/issues_tenant/IssueDetailsScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/screens/messaging/MessagingScreen.tsx
  firebase/firestore/firestore.ts
  jest/setup.js
  package-lock.json
  package.json
  styles/styles.ts
  types/types.ts
Labels: enhancement

#212 Add filtering capabilities to Landlord Issues List
  app/__tests__/unit/LandlordListIssues.test.tsx
  app/screens/issues_landlord/LandlordListIssuesScreen.tsx
  package-lock.json
Labels: enhancement

#215 Figma Newsfeed PR
  app/screens/laundry_machines/ManageMachinesScreen.tsx
Labels: figma

#248 Snitch Mode Feature 🤫
  app/Navigators/LandlordDrawerNavigator.tsx
  app/Navigators/TenantHomeDrawerNavigator.tsx
  app/__tests__/screens/SnitchMode/SnitchModeScreen.test.tsx
  app/screens/SnitchMode/SnitchModeScreen.tsx
  app/screens/SnitchMode/WaveformVisualizer.tsx
  package-lock.json
  styles/styles.ts
Labels: enhancement

#217 Switch to expo notification for the timer of the Washing Machines
  app/__tests__/WashingMachineScreen.test.tsx
  app/__tests__/unit/NotificationWashingMachine.test.tsx
  app/screens/laundry_machines/WashingMachineScreen.tsx
  package-lock.json
  package.json
  types/types.ts
Labels: enhancement

#253 Hot fix for Landlord Dashboard, Landlord Maintenance Issues, Residence Stack and Residence Creation Screen
  app/Navigators/IssueStackNavigator.tsx
  app/__mocks__/styleMock.ts
  app/__tests__/MessagingScreen.test.tsx
  app/__tests__/ReportScreen.test.tsx
  app/__tests__/ResidenceCreationScreen.test.tsx
  app/__tests__/ResidenceItem.test.tsx
  app/__tests__/ResidenceListScreen.test.tsx
  app/__tests__/unit/LandlordListIssues.test.tsx
  app/components/ResidenceItem.tsx
  app/screens/issues_landlord/LandlordListIssuesScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/screens/landlord/LandlordDashboard.tsx
  app/screens/landlord/ResidenceCreationScreen.tsx
  app/screens/landlord/ResidenceListScreen.tsx
  app/screens/messaging/MessagingScreen.tsx
  firebase/firestore/firestore.ts
  styles/styles.ts
  types/types.ts
Labels: bug, enhancement, testing

#255 Improving Overall coverage for untested code
  app/Navigators/LandlordDrawerNavigator.tsx
  app/Navigators/TenantHomeDrawerNavigator.tsx
  app/__tests__/CustomBubble.test.tsx
  app/__tests__/IssueStackLandlord.test.tsx
  app/__tests__/LandlordDrawerNavigator.test.tsx
  app/__tests__/TenantHomeDrawerNavigator.test.tsx
  app/__tests__/chat.test.ts
  app/__tests__/chat.test.tsx
Labels: testing

#257 Fix bugs concerning issue details and messaging
  app/__tests__/MessagingScreen.test.tsx
  app/screens/auth/SignInScreen.tsx
  app/screens/issues_tenant/IssueDetailsScreen.tsx
  app/screens/messaging/MessagingScreen.tsx
  types/types.ts
Labels: bug, testing

#260 Fix/dashboard&keyboard
  app/Navigators/TenantHomeDrawerNavigator.tsx
  app/__tests__/LandloardDashboard.test.tsx
  app/__tests__/MyRentScreen.test.tsx
  app/__tests__/ReportScreen.test.tsx
  app/__tests__/SharedElementsScreen.test.tsx
  app/__tests__/SubrentScreen.test.tsx
  app/__tests__/TenantFormScreen.test.tsx
  app/__tests__/TenantHomeDrawerNavigator.test.tsx
  app/__tests__/unit/LandlordFormScreen.test.tsx
  app/screens/auth/LandlordFormScreen.tsx
  app/screens/auth/SignUpScreen.tsx
  app/screens/auth/TenantFormScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/screens/landlord/LandlordDashboard.tsx
  app/screens/tenant/MyRentScreen.tsx
  app/screens/tenant/SharedElementsScreen.tsx
  app/screens/tenant/SubrentScreen.tsx
  app/screens/tenant/index.ts
  package-lock.json
  package.json
Labels: bug, testing

#256 Feature/newsfeed screens
  app/Navigators/LandlordDrawerNavigator.tsx
  app/Navigators/TenantHomeDrawerNavigator.tsx
  app/__tests__/LandlordDrawerNavigator.test.tsx
  app/__tests__/ManageNewsfeedScreen.test.tsx
  app/__tests__/ReportScreen.test.tsx
  app/__tests__/ViewNewsfeedScreen.test.tsx
  app/__tests__/unit/ListIssuesScreen.test.tsx
  app/screens/issues_tenant/ListIssueScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/screens/landlord/LandlordDashboard.tsx
  app/screens/laundry_machines/ManageMachinesScreen.tsx
  app/screens/newsfeed/ManageNewsfeedScreen.tsx
  app/screens/newsfeed/ViewNewsfeedScreen.tsx
  firebase/firestore/firestore.ts
  package-lock.json
  package.json
  styles/styles.ts
  types/types.ts
Labels: enhancement

#249 Offline mode and Caching
  app/__tests__/IssueStackNavigator.test.tsx
  app/__tests__/LandloardDashboard.test.tsx
  app/__tests__/ManageMachinesScreen.test.tsx
  app/__tests__/ReportScreen.test.tsx
  app/__tests__/ResidenceCreationScreen.test.tsx
  app/__tests__/SituationReport.firebase.test.ts
  app/__tests__/SituationReport.test.ts
  app/__tests__/SituationReportCreationScreen.test.tsx
  app/__tests__/SituationReportScreenTest.test.tsx
  app/__tests__/SituationReportTest.test.tsx
  app/__tests__/TenantHomeDrawerNavigator.test.tsx
  app/__tests__/WashingMachineScreen.test.tsx
  app/__tests__/firebase.test.tsx
  app/__tests__/unit/ListIssuesScreen.test.tsx
  app/screens/issues_tenant/ListIssueScreen.tsx
  app/screens/issues_tenant/ReportScreen.tsx
  app/stores/NetworkStore.tsx
  firebase/firebase.ts
  firebase/firestore/firestore.ts
  jest/setup.js
  package-lock.json
  package.json
  types/types.ts
Labels: enhancement
